import { HeatpumpModel } from './types';

export const HEATPUMP_MODELS: HeatpumpModel[] = [
  {
    id: 'altherma-3h-mt',
    name: 'Altherma 3 H MT ECH2O',
    settings: {
      '0-00': {
        description: 'Leaving water value for high ambient temp. for LWT add zone heating WD curve.',
        default: (settings) => (settings['2-0C'] === 0 ? 25 : 35),
        range: 'min(45,[9-06])°C, step: 1°C',
        rw: true,
      },
      '0-01': {
        description: 'Leaving water value for low ambient temp. for LWT add zone heating WD curve.',
        default: (settings) => (settings['2-0C'] === 0 ? 35 : (settings['2-0c'] === 1 ? 45 : 65)),
        range: '[9-05]~[9-06]°C, step: 1°C',
        rw: true,
      },
      '0-02': {
        description: 'High ambient temp. for LWT add zone heating WD curve.',
        default: 15,
        range: '10~25°C, step: 1°C',
        rw: true,
      },
      '0-03': {
        description: 'Low ambient temp. for LWT add zone heating WD curve.',
        default: -15,
        range: '-40~5°C, step: 1°C',
        rw: true,
      },
      '0-04': {
        description: 'Leaving water value for high ambient temp. for LWT add zone cooling WD curve.',
        default: (settings) => (settings['2-0C'] === 1 ? 7 : 18),
        range: '[9-07]~[9-08]°C, step: 1°C',
        rw: true,
      },
      '0-05': {
        description: 'Leaving water value for low ambient temp. for LWT add zone cooling WD curve.',
        default: 22,
        range: '[9-07]~[9-08]°C, step: 1°C',
        rw: true,
      },
      '0-06': {
        description: 'High ambient temp. for LWT add zone cooling WD curve.',
        default: 35,
        range: '25~43°C, step: 1°C',
        rw: true,
      },
      '0-07': {
        description: 'Low ambient temp. for LWT add zone cooling WD curve.',
        default: 20,
        range: '10~25°C, step: 1°C',
        rw: true,
      },
      '0-08': {
        description: 'Leaving water value for high ambient temp. for DHW WD curve.',
        default: 55,
        range: '35~[6-0E]°C, step: 1°C',
        rw: true,
      },
      '0-0C': {
        description: 'Leaving water value for low ambient temp. for DHW WD curve.',
        default: 60,
        range: 'Min(45~[6-0E])～[6-0E]°C, step: 1°C',
        rw: true,
      },
      '0-0D': {
        description: 'High ambient temp. for DHW WD curve.',
        default: 15,
        range: '10~25°C, step: 1°C',
        rw: true,
      },
      '0-0E': {
        description: 'Low ambient temp. for DHW WD curve.',
        default: -10,
        range: '-40~5°C, step: 1°C',
        rw: true,
      },
      '1-00': {
        description: 'Low ambient temp. for LWT main zone heating WD curve.',
        default: -15,
        range: '-40~5°C, step: 1°C',
        rw: true,
      },
      '1-01': {
        description: 'High ambient temp. for LWT main zone heating WD curve.',
        default: 15,
        range: '10~25°C, step: 1°C',
        rw: true,
      },
      '1-02': {
        description: 'Leaving water value for low ambient temp. for LWT main zone heating WD curve.',
        default: (settings) => (settings['2-0C'] === 0 ? 35 : (settings['2-0c'] === 1 ? 45 : 60)),
        range: '[9-01]~[9-00], step: 1°C',
        rw: true,
      },
      '1-03': {
        description: 'Leaving water value for high ambient temp. for LWT main zone heating WD curve.',
        default: (settings) => (settings['2-0C'] === 0 ? 25 : (settings['2-0c'] === 1 ? 35 : 40)),
        range: '[9-01]~min(45, [9-00])°C, step: 1°C',
        rw: true,
      },
      '1-04': {
        description: 'Weather dependent cooling of the main leaving water temperature zone.',
        default: 1,
        range: '0=Disabled, 1=Enabled',
        rw: true,
      },
      '1-05': {
        description: 'Weather dependent cooling of the additional leaving water temperature zone.',
        default: 1,
        range: '0=Disabled, 1=Enabled',
        rw: true,
      },
      '1-06': {
        description: 'Low ambient temp. for LWT main zone cooling WD curve.',
        default: 20,
        range: '10~25°C, step: 1°C',
        rw: true,
      },
      '1-07': {
        description: 'HIgh ambient temp. for LWT main zone cooling WD curve.',
        default: 35,
        range: '25~43°C, step: 1°C',
        rw: true,
      },
      '1-08': {
        description: 'Leaving water value for low ambient temp. for LWT main zone cooling WD curve.',
        default: 22,
        range: '[9-03]~[9-02]°C, step: 1°C',
        rw: true,
      },
      '1-09': {
        description: 'Leaving water value for high ambient temp. for LWT main zone cooling WD curve.',
        default: (settings) => (settings['2-0C'] === 1 ? 7 : 18),
        range: '[9-03]~[9-02]°C, step: 1°C',
        rw: true,
      },
      '1-0A': {
        description: 'What is the averaging time for the outdoor temp?',
        default: 0,
        range: '0=No averaging, 1=12 hours, 2=24 hours, 3=48 hours, 4=72 hours',
        rw: true,
      },
      '1-0B': {
        description: 'What is the desired delta T in heating for the main zone?',
        default: (settings) => (settings['2-0C'] === 2 ? 10 : 5),
        range: '3~10°C, step: 1°C',
        rw: true,
      },
      '1-0C': {
        description: 'What is the desired delta T in heating for the additional zone?',
        default: (settings) => (settings['2-0D'] === 2 ? 10 : 5),
        range: '3~10°C, step: 1°C',
        rw: true,
      },
      '1-0D': {
        description: 'What is the desired delta T in cooling for the main zone?',
        default: 5,
        range: '3~10°C, step: 1°C',
        rw: true,
      },
      '1-0E': {
        description: 'What is the desired delta T in cooling for the additional zone?',
        default: 5,
        range: '3~10°C, step: 1°C',
        rw: true,
      },
      '2-00': {
        description: 'When should the disinfection function be executed?',
        default: 5,
        range: '0: Each day, 1: Monday, 2: Tuesday, 3: Wednesday, 4: Thursday, 5: Friday, 6: Saturday, 7: Sunday',
        rw: true,
      },
      '2-01': {
        description: 'Should the disinfection function be executed?',
        default: 0,
        range: '0=No, 1=Yes',
        rw: true,
      },
      '2-02': {
        description: 'When should the disinfection function start?',
        default: 1,
        range: '0~23 hour, step: 1 hour',
        rw: true,
      },
      '2-03': {
        description: 'What is the disinfection target temperature?',
        default: 60,
        range: '60',
        rw: true,
      },
      '2-04': {
        description: 'How long must the tank temperature be maintained?',
        default: 40,
        range: '40~60 min, step: 5 min',
        rw: true,
      },
      '2-05': {
        description: 'Room antifrost temperature',
        default: 8,
        range: '4~16°C, step: 1°C',
        rw: true,
      },
      '2-06': {
        description: 'Room frost protection',
        default: 1,
        range: '0=No, 1=Yes',
        rw: true,
      },
      '2-09': {
        description: 'Adjust the offset on the measured room temperature',
        default: 0,
        range: '-5~5°C, step: 0,5°C',
        rw: true,
      },
      '2-0A': {
        description: 'Adjust the offset on the measured room temperature',
        default: 0,
        range: '-5~5°C, step: 0,5°C',
        rw: true,
      },
      '2-0B': {
        description: 'What is the required offset on the measured outdoor temp.?',
        default: 0,
        range: '-5~5°C, step: 0,5°C',
        rw: true,
      },
      '2-0C': {
        description: 'What emitter type is connected to the main LWT zone?',
        default: 0,
        range: '0=Underfloor heating, 1=Fancoil, 2=Radiator',
        rw: true,
      },
      '2-0D': {
        description: 'What emitter type is connected to the additional LWT zone?',
        default: 2,
        range: '0=Underfloor heating, 1=Fancoil, 2=Radiator',
        rw: true,
      },
      '2-0E': {
        description: 'What is the maximum allowed current over the heatpump?',
        default: 50,
        range: '20~50 A, step: 1 A',
        rw: true,
      },
      '3-00': {
        description: 'Is auto restart of the unit allowed?',
        default: 1,
        range: '0=No, 1=Yes',
        rw: true,
      },
      '3-01': {
        description: '(Undocumented)',
        default: 0,
        range: '0',
        rw: true,
      },
      '3-02': {
        description: '(Undocumented)',
        default: 1,
        range: '1',
        rw: true,
      },
      '3-03': {
        description: '(Undocumented)',
        default: 4,
        range: '4',
        rw: true,
      },
      '3-04': {
        description: '(Undocumented)',
        default: 2,
        range: '2',
        rw: true,
      },
      '3-05': {
        description: '(Undocumented)',
        default: 1,
        range: '1',
        rw: true,
      },
      '3-06': {
        description: 'What is the maximum desired room temperature in heating?',
        default: 30,
        range: '18~30°C, step: 1°C',
        rw: true,
      },
      '3-07': {
        description: 'What is the mimimum desired room temperature in heating?',
        default: 12,
        range: '12~18°C, step: 1°C',
        rw: true,
      },
      '3-08': {
        description: 'What is the maximum desired room temperature in cooling?',
        default: 35,
        range: '25~35°C, step: 1°C',
        rw: true,
      },
      '3-09': {
        description: 'What is the minimum desired room temperature in cooling?',
        default: 15,
        range: '15~25°C, step: 1°C',
        rw: true,
      },
      '3-0A': {
        description: 'What is the pump model',
        default: 0,
        range: '0=pump model 0, 1=pump model 1',
        rw: false,
      },
      '4-00': {
        description: 'What is the BUH operation mode?',
        default: 1,
        range: '0=Disabled, 1=Enabled, 2=Only DHW',
        rw: true,
      },
      '4-01': {
        description: 'Which electric heater has priority?',
        default: 0,
        range: '0=None (Both in parallel), 1=BSH, 2=BUH',
        rw: true,
      },
      '4-02': {
        description: 'Below which outdoor temperature is heating allowed?',
        default: 35 ,
        range: '14~35°C, step: 1°C',
        rw: true,
      },
      '4-03': {
        description: 'Operation permission of the booster heater.',
        default: 3,
        range: '0: Restricted, 1: Allowed, 2: Overlap, 3: Compressor off, 4: Legionella only',
        rw: true,
      },
      '4-04': {
        description: 'Water pipe freeze prevention',
        default: 0,
        range: '0: Continuous pump operation, 1: Non continuous pump operation, 2: OFF',
        rw: true,
      },
      '4-05': {
        description: '(Undocumented)',
        default: 0,
        range: '0',
        rw: true,
      },
      '4-06': {
        description: 'Emergency',
        default: 3,
        range: '0: Manual, 1: Automatic, 2: Auto red SH/ DHW ON, 3: Auto red SH/ DHW OFF, 4: Auto normal SH/ DHW OFF',
        rw: true,
      },
      '4-07': {
        description: '(Undocumented)',
        default: 3,
        range: '3',
        rw: true,
      },
      '4-08': {
        description: 'Which power limitation mode is required on the system?',
        default: 0,
        range: '0: No limitation, 1: Continuous, 2: Digital inputs, 3: Load Monitor',
        rw: true,
      },
      '4-09': {
        description: 'Which power limitation type is required?',
        default: 1,
        range: '0: Current, 1: Power',
        rw: true,
      },
      '4-0A': {
        description: 'Backup heater configuration',
        default: 0,
        range: '0: 1 (3V, BUH-less), 1: 1/1+2 (6V, 9W), 2: 1/2, 3: 1/2 + 1/1+2 in emergency',
        rw: true,
      },
      '4-0B': {
        description: 'Automatic cooling/heating changeover hysteresis.',
        default: 1,
        range: '1~10°C, step: 0,5°C',
        rw: true,
      },
      '4-0D': {
        description: 'Automatic cooling/heating changeover offset.',
        default: 3,
        range: '1~10°C, step: 0,5°C',
        rw: true,
      },
      '4-0E': {
        description: '(Undocumented)',
        default: 6,
        range: '6',
        rw: false,
      },
      '5-00': {
        description: 'Equilibrium: Deactivate backup heater (or external backup heat source in case of a bivalent system) above the equilibrium temperature for space heating?',
        default: 1,
        range: '0=No, 1=Yes',
        rw: true,
      },
      '5-01': {
        description: 'What is the equilibrium temperature for the building?',
        default: 0,
        range: '-15~35°C, step: 1°C',
        rw: true,
      },
      '5-02': {
        description: 'Space heating priority.',
        default: 0,
        range: '0: Disabled, 1: Enabled',
        rw: true,
      },
      '5-03': {
        description: 'Space heating priority temperature.',
        default: 0,
        range: '-15~35°C, step: 1°C',
        rw: true,
      },
      '5-04': {
        description: 'Set point correction for domestic hot water temperature.',
        default: 10,
        range: '0~20°C, step: 1°C',
        rw: true,
      },
      '5-05': {
        description: 'What is the requested limit for DI1 (in Amp)?',
        default: 50,
        range: '0~50 A, step: 1 A',
        rw: true,
      },
      '5-06': {
        description: 'What is the requested limit for DI2 (in Amp)?',
        default: 50,
        range: '0~50 A, step: 1 A',
        rw: true,
      },
      '5-07': {
        description: 'What is the requested limit for DI3 (in Amp)?',
        default: 50,
        range: '0~50 A, step: 1 A',
        rw: true,
      },
      '5-08': {
        description: 'What is the requested limit for DI4 (in Amp)?',
        default: 50,
        range: '0~50 A, step: 1 A',
        rw: true,
      },
      '5-09': {
        description: 'What is the requested limit for DI1 (in kW)?',
        default: 20,
        range: '0~20 kW, step: 0,5 kW',
        rw: true,
      },
      '5-0A': {
        description: 'What is the requested limit for DI2 (in kW)?',
        default: 20,
        range: '0~20 kW, step: 0,5 kW',
        rw: true,
      },
      '5-0B': {
        description: 'What is the requested limit for DI3 (in kW)?',
        default: 20,
        range: '0~20 kW, step: 0,5 kW',
        rw: true,
      },
      '5-0C': {
        description: 'What is the requested limit for DI4 (in kW)?',
        default: 20,
        range: '0~20 kW, step: 0,5 kW',
        rw: true,
      },
      '5-0D': {
        description: 'Backup heater voltage',
        default: 0,
        range: '0: 230V, 1~ (3V, 6V, BUH-less), 2: 400V, 3~ (9W)',
        rw: false,
      },
      '5-0E': {
        description: '(Undocumented)',
        default: 1,
        range: '1',
        rw: true,
      },
      '6-00': {
        description: 'The temperature difference determining the heat pump ON temperature.',
        default: 8,
        range: '2~40°C, step: 1°C',
        rw: true,
      },
      '6-01': {
        description: 'The temperature difference determining the heat pump OFF temperature.',
        default: 0,
        range: '0~10°C, step: 1°C',
        rw: true,
      },
      '6-02': {
        description: 'What is the capacity of the booster heater?',
        default: 0,
        range: '0~10kW, step: 0,2kW',
        rw: true,
      },
      '6-03': {
        description: 'What is the capacity of the backup heater step 1?',
        default: 0,
        range: '0~10kW, step: 0,2kW. Defaults: 0kW (BUH-less), 2kW (6V), 3kW (3V, 9W, BUH-less)',
        rw: true,
      },
      '6-04': {
        description: 'What is the capacity of the backup heater step 2?',
        default: 0,
        range: '0~10kW, step: 0,2kW. Defaults: 0kW (3V), 3kW (BUH-less), 4kW (6V), 6kW (9W)',
        rw: true,
      },
      '6-07': {
        description: '(Undocumented)',
        default: 0,
        range: '0',
        rw: true,
      },
      '6-08': {
        description: 'What is the hysteresis to be used in reheat mode?',
        default: 10,
        range: '2~20°C, step: 1°C',
        rw: true,
      },
      '6-09': {
        description: '(Undocumented)',
        default: 0,
        range: '0',
        rw: true,
      },
      '6-0A': {
        description: 'What is the desired comfort storage temperature?',
        default: 60,
        range: '30~[6-0E]°C, step: 1°C',
        rw: true,
      },
      '6-0B': {
        description: 'What is the desired eco storage temperature?',
        default: 45,
        range: '30~min(50, [6-0E])°C, step: 1°C',
        rw: true,
      },
      '6-0C': {
        description: 'What is the desired reheat temperature?',
        default: 45,
        range: '30~min(50, [6-0E])°C, step: 1°C',
        rw: true,
      },
      '6-0D': {
        description: 'What is the desired DHW production type?',
        default: 0,
        range: '0: Reheat only, 3: scheduled reheat',
        rw: true,
      },
      '6-0E': {
        description: 'What is the maximum temperature setpoint?',
        default: 65,
        range: '40~ 75°C, step: 1°C',
        rw: true,
      },
      '7-00': {
        description: 'Domestic hot water booster heater overshoot temperature.',
        default: 0,
        range: '0~4°C, step: 1°C',
        rw: true,
      },
      '7-01': {
        description: 'Domestic hot water booster heater hysteresis.',
        default: 2,
        range: '2~40°C, step: 1°C',
        rw: true,
      },
      '7-02': {
        description: 'How many leaving water temperature zones are there?',
        default: 0,
        range: '0: 1 LWT zone, 1: 2 LWT zones',
        rw: true,
      },
      '7-03': {
        description: '(Undocumented)',
        default: 2.5,
        range: '2.5',
        rw: false,
      },
      '7-04': {
        description: '(Undocumented)',
        default: 0,
        range: '0',
        rw: false,
      },
      '7-05': {
        description: 'Boiler efficiency',
        default: 0,
        range: '0: Very high, 1: High, 2: Medium, 3: Low, 4: Very low',
        rw: true,
      },
      '7-06': {
        description: 'Compressor forced OFF',
        default: 0,
        range: '0: Disabled, 1: Enabled',
        rw: true,
      },
      '7-07': {
        description: 'BBR16 activation (settings are only visible when the language of the user interface is set to Swedish)',
        default: 0,
        range: '0: Disabled, 1: Enabled',
        rw: true,
      },
      '7-08': {
        description: 'DHW stratification',
        default: 0 ,
        range: '0: Disabled (Default on 300L), 1: Enabled (Default on 500L)',
        rw: true,
      },
      '7-09': {
        description: '(Undocumented)',
        default: 20,
        range: '20',
        rw: true,
      },
      '7-0A': {
        description: 'Additional zone fixed pump PWM, in case a bizone kit is installed.',
        default: 95,
        range: '20~95%, step 5%',
        rw: true,
      },
      '7-0B': {
        description: 'Main zone fixed pump PWM, in case a bizone kit is installed.',
        default: 95,
        range: '20~95%, step 5%',
        rw: true,
      },
      '7-0C': {
        description: 'Time needed by the mixing valve to turn from one side to the other, in case a bizone kit is installed.',
        default: 125,
        range: '20~300 seconds, step 5 sec',
        rw: true,
      },
      '7-0D': {
        description: 'Hysteresis value used to control the tank bivalent in case it’s supporting space heating operation',
        default: 4,
        range: '2~20, step 0,5 °C',
        rw: true,
      },
      '7-0E': {
        description: 'Offset on the setpoint to determine when the tank is high enough to go the excess state',
        default: 7,
        range: '2~22, step 0,5 °C',
        rw: true,
      },
      '8-00': {
        description: 'Minimum running time for domestic hot water operation.',
        default: 1,
        range: '0~20 min, step 1 min',
        rw: true,
      },
      '8-01': {
        description: 'Maximum running time for domestic hot water operation.',
        default: 30,
        range: '5~95 min, step: 5 min',
        rw: true,
      },
      '8-02': {
        description: 'Anti-recycling time.',
        default: 0.5,
        range: '0~10 hour, step: 0,5 hour',
        rw: true,
      },
      '8-03': {
        description: 'Booster heater delay timer.',
        default: 50,
        range: '20~95 min, step: 5 min',
        rw: true,
      },
      '8-04': {
        description: 'Additional running time for the maximum running time.',
        default: 95,
        range: '0~95 min, step: 5 min',
        rw: true,
      },
      '8-05': {
        description: 'Allow modulation of the LWT to control the room temp?',
        default: 0,
        range: '0:No, 1:Yes',
        rw: true,
      },
      '8-06': {
        description: 'Leaving water temperature maximum modulation.',
        default: 5,
        range: '0~10°C, step: 1°C',
        rw: true,
      },
      '8-07': {
        description: 'What is the desired comfort main LWT in cooling?',
        default: 18,
        range: '[9-03]~[9-02], step: 1°C',
        rw: true,
      },
      '8-08': {
        description: 'What is the desired eco main LWT in cooling?',
        default: 20,
        range: '[9-03]~[9-02], step: 1°C',
        rw: true,
      },
      '8-09': {
        description: 'What is the desired comfort main LWT in heating?',
        default: 35,
        range: '[9-01]~[9-00], step: 1°C',
        rw: true,
      },
      '8-0A': {
        description: 'What is the desired eco main LWT in heating?',
        default: 33,
        range: '[9-01]~[9-00], step: 1°C',
        rw: true,
      },
      '8-0B': {
        description: '(Undocumented)',
        default: 13,
        range: '13',
        rw: true,
      },
      '8-0C': {
        description: '(Undocumented)',
        default: 10,
        range: '10',
        rw: true,
      },
      '8-0D': {
        description: '(Undocumented)',
        default: 16,
        range: '16',
        rw: true,
      },
      '9-00': {
        description: 'What is the maximum desired LWT for main zone in heating?',
        default: (settings) => (settings['2-0C'] === 2 ? 65 : 55),
        range: (settings) => (settings['2-0C'] === 2 ? "37~65, step: 1°C" : "37~55, step: 1°C"),
        rw: true,
      },
      '9-01': {
        description: 'What is the mimimum desired LWT for main zone in heating?',
        default: 25,
        range: '15~37°C, step: 1°C',
        rw: true,
      },
      '9-02': {
        description: 'What is the maximum desired LWT for main zone in cooling?',
        default: 22,
        range: '18~22°C, step: 1°C',
        rw: true,
      },
      '9-03': {
        description: 'What is the mimimum desired LWT for main zone in cooling?',
        default: 7,
        range: '5~18°C, step: 1°C',
        rw: true,
      },
      '9-04': {
        description: 'Leaving water temperature overshoot temperature.',
        default: 2,
        range: '1~4°C, step: 1°C',
        rw: true,
      },
      '9-05': {
        description: 'What is the mimimum desired LWT for add. zone in heating?',
        default: 25,
        range: '15~37°C, step: 1°C',
        rw: true,
      },
      '9-06': {
        description: 'What is the maximum desired LWT for add. zone in heating?',
        default: (settings) => (settings['2-0C'] === 2 ? 65 : 55),
        range: (settings) => (settings['2-0C'] === 2 ? "37~65, step: 1°C" : "37~55, step: 1°C"),
        rw: true,
      },
      '9-07': {
        description: 'What is the mimimum desired LWT for add. zone in cooling?',
        default: 7,
        range: '5~18°C, step: 1°C',
        rw: true,
      },
      '9-08': {
        description: 'What is the maximum desired LWT for add. zone in cooling?',
        default: 22,
        range: '18~22°C, step: 1°C',
        rw: true,
      },
      '9-09': {
        description: 'What is the allowed LWT undershoot during cooling start-up?',
        default: 18,
        range: '1~18°C, step: 1°C',
        rw: true,
      },
      '9-0A': {
        description: 'What is the room buffering temperature in heating?',
        default: 23,
        range: '[3-07]～[3-06]°C, step: 0,5°C',
        rw: true,
      },
      '9-0B': {
        description: 'What is the room buffering temperature in Cooling?',
        default: 23,
        range: '[3-09]～[3-08]°C, step: 0,5°C',
        rw: true,
      },
      '9-0C': {
        description: 'Room temperature hysteresis.',
        default: 1,
        range: '1~6°C, step: 0,5°C',
        rw: true,
      },
      '9-0D': {
        description: 'Pump speed limitation',
        default: 6,
        range: '0~8, step:1. 0: No limitation, 1~4: 90~60% pump speed, 5~8: 90~60% pump speed during sampling, 6 80% pump speed during sampling',
        rw: true,
      },
      '9-0E': {
        description: '(Undocumented)',
        default: 6,
        range: '6',
        rw: true,
      },
      'C-00': {
        description: 'Domestic heating water priority.',
        default: 1,
        range: '0: Solar priority, 1: Heat pump priority',
        rw: true,
      },
      'C-01': {
        description: '(Undocumented)',
        default: 0,
        range: '0',
        rw: true,
      },
      'C-02': {
        description: 'Is an external backup heat source connected?',
        default: 0,
        range: '0 none, 1 bivalent through header, 2 tank DHW bivalent (*B* models), 3 tank heating + DHW bivalent',
        rw: true,
      },
      'C-03': {
        description: 'Bivalent activation temperature.',
        default: 0,
        range: '-25~25°C, step: 1°C',
        rw: true,
      },
      'C-04': {
        description: 'Bivalent hysteresis temperature.',
        default: 3,
        range: '2~10°C, step 1°C',
        rw: true,
      },
      'C-05': {
        description: 'What is the thermo request contact type for the main zone?',
        default: 2,
        range: '0: MMI requests (incl. quick logic), 1: 1 contact, 2: 2 contacts',
        rw: true,
      },
      'C-06': {
        description: 'What is the thermo request contact type for the add. zone?',
        default: 2,
        range: '0: MMI requests (incl. quick logic), 1: 1 contact, 2: 2 contacts',
        rw: true,
      },
      'C-07': {
        description: 'What is the unit control method in space operation?',
        default: 0,
        range: '0: LWT control, 1: Ext RT control, 2: RT control',
        rw: true,
      },
      'C-08': {
        description: 'Which type of external sensor is installed?',
        default: 0,
        range: '0: No, 1: Outdoor sensor, 2: Room sensor',
        rw: true,
      },
      'C-09': {
        description: 'What is the required alarm output contact type?',
        default: 0,
        range: '0: Normally open, 1: Normally closed',
        rw: true,
      },
      'C-0A': {
        description: '(Undocumented)',
        default: 0,
        range: '0',
        rw: true,
      },
      'C-0B': {
        description: '(Undocumented)',
        default: 0,
        range: '0',
        rw: true,
      },
      'C-0C': {
        description: '(Undocumented)',
        default: 0,
        range: '0',
        rw: true,
      },
      'C-0D': {
        description: '(Undocumented)',
        default: 0,
        range: '0',
        rw: true,
      },
      'C-0E': {
        description: '(Undocumented)',
        default: 0,
        range: '0',
        rw: true,
      },
      'D-00': {
        description: 'Which heaters are permitted if prefer. kWh rate PS is cut?',
        default: 0,
        range: '0: None, 1: BSH only, 2: BUH only, 3: All heaters',
        rw: true,
      },
      'D-01': {
        description: 'Contact type of preferential kWh rate PS installation?',
        default: 0,
        range: '0: No, 1: Active open, 2: Active closed, 3: Smart Grid',
        rw: true,
      },
      'D-02': {
        description: 'Which type of DHW pump is installed?',
        default: 0,
        range: '0: No DHW pump, 1: Instant hot water, 2: Disinfection, 3: Circulation, 4: Circulation and disinfection',
        rw: true,
      },
      'D-03': {
        description: 'Leaving water temperature compensation around 0°C.',
        default: 1,
        range: '0: No, 1: increase 2°C, span 4°C, 2: increase 4°C, span 4°C, 3: increase 2°C, span 8°C, 4: increase 4°C, span 8°C',
        rw: true,
      },
      'D-04': {
        description: 'Is a demand PCB connected?',
        default: 0,
        range: '0: No, 1: Pwr consmp ctrl',
        rw: true,
      },
      'D-05': {
        description: 'Is the pump allowed to run if prefer. kWh rate PS is cut?',
        default: 1,
        range: '0: Forced off, 1: As normal',
        rw: true,
      },
      'D-07': {
        description: 'Is a solar kit connected?',
        default: 2,
        range: '0: No, 1: Solar for DHW, 2: Solar for DHW and SH',
        rw: true,
      },
      'D-08': {
        description: 'Is an external kWh meter used for power measurement?',
        default: 0,
        range: '0: No, 1: 0,1 pulse/kWh, 2: 1 pulse/kWh, 3: 10 pulse/kWh, 4: 100 pulse/kWh, 5: 1000 pulse/kWh',
        rw: true,
      },
      'D-09': {
        description: 'Is an external kWh meter used for power measurement, kWh meter used for smart grid or a gas meter for hybrid unit?',
        default: 0,
        range: '0: No, 1: 0,1 pulse/kWh, 2: 1 pulse/kWh, 3: 10 pulse/kWh, 4: 100 pulse/kWh, 5: 1000 pulse/kWh, 6: 100 pulse/kWh (PV meter), 7: 1000 pulse/kWh (PV meter), 8: 1 pulse/m³ (gas monitoring), 9: 10 pulse/m³ (gas monitoring), 10: 100 pulse/m³ (gas monitoring)',
        rw: true,
      },
      'D-0A': {
        description: '(Undocumented)',
        default: 0,
        range: '0',
        rw: false,
      },
      'D-0B': {
        description: '(Undocumented)',
        default: 2,
        range: '2',
        rw: false,
      },
      'D-0C': {
        description: '(Undocumented)',
        default: 0,
        range: '0',
        rw: false,
      },
      'D-0D': {
        description: '(Undocumented)',
        default: 0,
        range: '0',
        rw: false,
      },
      'D-0E': {
        description: '(Undocumented)',
        default: 0,
        range: '0',
        rw: false,
      },
      'E-00': {
        description: 'Which type of unit is installed?',
        default: 0,
        range: '0: LT split, 1-5: undocumented',
        rw: false,
      },
      'E-01': {
        description: 'Which type of compressor is installed?',
        default: 1,
        range: '1',
        rw: false,
      },
      'E-02': {
        description: 'What is the indoor unit software type?',
        default: 1,
        range: '0: Reversible (Models *X*), 1: Heating only (Models *H*)',
        rw: false,
      },
      'E-03': {
        description: 'What is the number of backup heater steps?',
        default: 0,
        range: '0: no heater (BUH-less) 1: ext heater, 2: 3V, 3: 6V, 4: 9W',
        rw: true,
      },
      'E-04': {
        description: 'Is the power saving function available on the outdoor unit?',
        default: 1,
        range: '0:No, 1:Yes',
        rw: false,
      },
      'E-05': {
        description: 'Can the system prepare domestic hot water?',
        default: 1,
        range: '0:No, 1:Yes',
        rw: false,
      },
      'E-06': {
        description: '(Undocumented)',
        default: 1,
        range: '1',
        rw: true,
      },
      'E-07': {
        description: 'What kind of DHW tank is installed?',
        default: 4,
        range: '0: OSO tank 150/180, 1: FS with BUH, 2: FS with BSH, 3: OSO tank 200/250/300, 4: Rotex without BSH (HYB), 5: Rotex with BSH, 6: Third party tank for HYB, 7: Third party tank, coil >= 1,05m², 8: Third party tank, coil >= 1,8m²',
        rw: true,
      },
      'E-08': {
        description: 'Power saving function for outdoor unit.',
        default: 1,
        range: '0: disabled, 1: Enabled',
        rw: true,
      },
      'E-09': {
        description: '(Undocumented)',
        default: 1,
        range: '1',
        rw: false,
      },
      'E-0A': {
        description: 'Tank volume',
        default: 30,
        range: '30 (300L), 50 (500L)',
        rw: false,
      },
      'E-0B': {
        description: 'Is a bizone kit installed?',
        default: 0,
        range: '0: Not installed, 1: undefined, 2: Bizone kit installed',
        rw: true,
      },
      'E-0C': {
        description: 'What bizone system type is installed?',
        default: 0,
        range: '0: Without hydraulic separator / no direct pump, 1: With hydraulic separator / no direct pump, 2: With hydraulic separator / with direct pump',
        rw: true,
      },
      'E-0D': {
        description: 'Is the system filled with glycol?',
        default: 0,
        range: '0:No, 1:Yes',
        rw: true,
      },
      'E-0E': {
        description: '(Undocumented)',
        default: 0,
        range: '0',
        rw: true,
      },
      'F-00': {
        description: 'Pump operation allowed outside range.',
        default: 0,
        range: '0: Disabled, 1:Enabled',
        rw: true,
      },
      'F-01': {
        description: 'Above which outdoor temperature is cooling allowed?',
        default: 20,
        range: '10~35°C, step: 1°C',
        rw: true,
      },
      'F-02': {
        description: '(Undocumented)',
        default: 3,
        range: '3',
        rw: true,
      },
      'F-03': {
        description: '(Undocumented)',
        default: 5,
        range: '5',
        rw: true,
      },
      'F-04': {
        description: '(Undocumented)',
        default: 0,
        range: '0',
        rw: true,
      },
      'F-05': {
        description: '(Undocumented)',
        default: 0,
        range: '0',
        rw: true,
      },
      'F-06': {
        description: 'Enable Tank Boiler?',
        default: 0,
        range: '0: Disabled, 1: Enabled',
        rw: true,
      },
      'F-07': {
        description: 'Efficiency calculation',
        default: 0,
        range: '0: Enabled, 1: Disabled',
        rw: true,
      },
      'F-08': {
        description: 'Continuous heating defrost enable',
        default: 0,
        range: '0: Disabled, 1: Enabled',
        rw: true,
      },
      'F-09': {
        description: 'Pump operation during flow abnormality.',
        default: 0,
        range: '0: Disabled, 1: Enabled',
        rw: true,
      },
      'F-0A': {
        description: '(Undocumented)',
        default: 0,
        range: '0',
        rw: true,
      },
      'F-0B': {
        description: 'Close shut-off valve during thermo OFF?',
        default: 0,
        range: '0: No, 1: Yes',
        rw: true,
      },
      'F-0C': {
        description: 'Close shut-off valve during cooling?',
        default: 1,
        range: '0: No, 1: Yes',
        rw: true,
      },
      'F-0D': {
        description: 'What is the pump operation mode?',
        default: 1,
        range: '0: Continuous, 1: Sample, 2: Request',
        rw: true,
      },
      'F-0E': {
        description: 'Tank heating support_max',
        default: 20,
        range: '10~35 kW, step: 1kW',
        rw: true,
      },
    },
  },
];